[package]
name = "rust-pentago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { version = "0.21.0", features = ["all-widgets"]}
crossterm = "0.26"
